name: AI Newsletter Update

on:
  schedule:
    # Runs at 7 AM UTC every day
    - cron: '0 7 * * *'
  workflow_dispatch:
    # Allows manual triggering for testing

jobs:
  update-newsletter:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Debug files in directory
      run: |
        echo "Listing all Python files:"
        find . -name "*.py" -type f
        echo "Listing all files in current directory:"
        ls -la

    - name: Debug Google API Authentication
      env:
        GOOGLE_CREDENTIALS: ${{ secrets.GOOGLE_CREDENTIALS }}
        DOCUMENT_ID: ${{ secrets.DOCUMENT_ID }}
        GITHUB_RUN_ID: ${{ github.run_id }}
      run: |
        echo "Running authentication test..."
        python debug_auth.py
      continue-on-error: true

    - name: Run newsletter agent
      env:
        GOOGLE_CREDENTIALS: ${{ secrets.GOOGLE_CREDENTIALS }}
        DOCUMENT_ID: ${{ secrets.DOCUMENT_ID }}
        GITHUB_RUN_ID: ${{ github.run_id }}
        # Enable verbose logging
        PYTHONVERBOSE: 1
      run: |
        echo "Running newsletter agent..."
        python newsletter_agent.py
      
    - name: Record run outcome
      run: |
        echo "Newsletter update completed at $(date)" > last_run.log
        
    - name: Commit last run log
      uses: stefanzweifel/git-auto-commit-action@v4
      with:
        commit_message: "Update newsletter run log"
        file_pattern: last_run.log